# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wataru's Portfolio
email: whashi44@gmail.com
image: /assets/images/portfolio/fea.png
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio for Wataru Hashimoto
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://whashi.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Wataru Hashimoto
icon: /assets/favicons/favicon.png
twitter:
  username: Wataru_Hashi1
  card: summary

twitter_username: jekyllrb
github_username:  whashi44
linkedin_username: whashimoto
kaggle_username: wataruhashimoto

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
